name: Deploy main branch

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    # - name: Add profile credentials to ~/.aws/credentials 
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: |
    #     aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    #     aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      env:
        MY_AWS_ROLE_ARN: ${{ secrets.MY_AWS_ROLE_ARN }} 
      with:
        role-to-assume: "$MY_AWS_ROLE_ARN"
        aws-region: us-east-1
    # - name: serverless config aws credentials
    #   uses: serverless/github-action@v3.2
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   with:
    #     args: --config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
    - run: cd ~/.aws && ls -al
    - run: yarn deploy:Prod
