name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - name: config aws credentials
      run: cd ~ && mkdir .aws && cd .aws && echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> credentials && echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> credentials && ls -al
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # - name: serverless config aws credentials
    #   uses: serverless/github-action@v3.2
    #   with:
    #     args: config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile rud --overwrite
    - run: yarn deploy:Prod
